### ISSUE TITLE
Random one pixel size errors, when converting a JPEG

### ISSUE THREAD

**Issue by juhavlintula** [Aries85/LightZone#204]
When I generated few background images (9×16) for my mobile phone and set "Fit within 2560 x 2560", some of the JPEGs are 1440×2560, but there are also images that are 1441×2560 or even 1440×2561. I have a feeling, that this is somehow related to the position from where the image is cropped.

-Juha

PS. I can share example images, if needed.

**Comment by ktgw0316** [comment]
@juhavlintula Would you test 8462d32? I'm going to merge the branch if it fixes this issue. If it doesn't work, please share the example images.

**Comment by juhavlintula** [comment]
The fix worked partially. Here is a link to Dropbox https://www.dropbox.com/sh/q4r3vx3prw2pl4b/AAABn0WNkaakNG9Xs4TTKTVHa?dl=0

The belfry is now correct 1440×2560 but the yellow house is still 1441×2560. Both images are cropped to 9×16.

**Comment by ktgw0316** [comment]
Hmm... Maybe I misunderstand something, but version size of the "IMG_3790_9x16_lzn.jpg" is 576 x 1024 on my side.

I overwrote "ResizeWidthOption" and "ResizeHightOption" values in the file from 1024 to 2560 using hex editor, then open and save it  again in LZ. The version size is now 1440 x 2560.

**Comment by juhavlintula** [comment]
Sorry, I was unclear and I didn't include the final JPG image. The problem is, when I run convert with "fit in", then the generated JPG is for the yellow house 1441×2560 and not 1440×2560 as it should be.

**Comment by ktgw0316** [comment]
Thank you for the clarification. I understand now. :) I'll look into it again.

**Comment by ktgw0316** [comment]
@juhavlintula I think 1792e7b fixes this issue. Would you test it again?

**Comment by juhavlintula** [comment]
It's still not working. The yellow house is still when I convert the _lzn file to JPG 1441×2560. 

When I start LightZone with ant -f linux/build.xml run, I get on the console message:
[java] This is LigthZone 4.1.7 (1792e7b), so I guess I have pulled the right version out of GitHub.

**Comment by ktgw0316** [comment]
Could you share the final JPG image?

**Comment by juhavlintula** [comment]
I have uploaded the final jpg also into Dropbox.

**Comment by juhavlintula** [comment]
I added there also another image (RAW, LZN and JPG) that should be 1:1, but is 3455×3454.

**Comment by ktgw0316** [comment]
I could reproduce the issue with the IMG_8774 on v4.1.7, but not on the 1792e7b. These are what I exactly did:

1. `ant -f linux/build.xml` 
1. `ant -f linux/build.xml run`
1. Select the IMG_8774_lzn.jpg in Browser
1. Select "Browse" -> "Convert..." menu
1. Set 3455 x 3455 pixels in Resize text boxes on Convert dialog
1. Click "Convert" button on the Convert dialog
1. Check size of the output JPEG

The size was 3455 x 3454 on v4.1.7, and 3455 x 3455 on 1792e7b.

Could you try `ant -f linux/build.xml clean` before `ant -f linux/build.xml` and `ant -f linux/build.xml run`?

**Comment by juhavlintula** [comment]
After I did clean, converted IMG_8774 is correct square 3455×3455. When I tried IMG_3790 and limited the output to 2560×2560, I still get 1441×2560.

**Comment by juhavlintula** [comment]
I also uploaded another almost square image that is 3456×3455. I converted during the same session as IMG_8774. I even reapplied 1:1 cropping to the lzn file, to eliminate my errors.

**Comment by ktgw0316** [comment]
I found another bug in Rendering.java, and fixed it, so at least the problem on IMG_8774 was fixed by 328d3e1. I also tried the IMG_3790 with the limit 1440x2560, and got 1440x2560 output.

**Comment by juhavlintula** [comment]
What did I do wrong? I pulled 328d3e1 and did even build clean, but I still get IMG_3790 out as 1441×2560. Other images in my Dropbox converted correctly.

**Comment by ktgw0316** [comment]
I have no idea what is wrong, so I added debug output code in a4bf19b. "/tmp/LZDebug328d3e1.xml" will be created when you run the a4bf19b with the IMG_3790. Could you send me that file?

**Comment by juhavlintula** [comment]
Here is the debug file (renamed to .log).

I did a clean build and then converted the IMG_3790. In the conversion dialog I had
– Resize to: Fit within 2560×2560
– Rendering intent: Perceptual
– Quality: 100%
– Pixels per Inch: 300

[LZDebug328d3e1.log](https://github.com/Aries85/LightZone/files/1392410/LZDebug328d3e1.log)

**Comment by ktgw0316** [comment]
Sorry for the late reply. How about e559f0d?

By the way, I couldn't set Fit within 2560×2560 for IMG_3790_9x16_lzn.jpg. Those values are automatically changed to 1440x2560 when I enter the values, and I think that it is correct behavior.

**Comment by juhavlintula** [comment]
It looks like we have been using different "Convert". You have been using the right click menu (image #1) and I have been using the Batch Processing in the top menu bar (image #2). The pop-up menu produces now a correct result (1440×2560), but the batch processing forces the image to 2560×2560 and streches it.
![lz convert](https://user-images.githubusercontent.com/18402158/32011735-4c431c70-b9be-11e7-99a9-534ac114cb97.png)
![lz batch processing](https://user-images.githubusercontent.com/18402158/32011759-56bb3318-b9be-11e7-8b41-8c7e4ee6d756.png)

**Comment by juhavlintula** [comment]
I also noted, that when I created a new _lzn file, it got stretched the same way as in the second image. The example is in the Dropbox folder "IMG_3790_9x16B_lzn.jpg".

**Comment by ktgw0316** [comment]
I hadn't noticed the difference between those two "Convert". Thank you again for the clarification.

I reverted some of my commits, then fixed scale calculation in commit 231ad93. I checked its results of both "Convert" menus with all the sample images you provided.

**Comment by juhavlintula** [comment]
I tested the version with some other images and it produced correct results. I got 1440×2560 images as well as some older ~squares are now perfect squares without one pixel difference in the dimensions.

**Comment by ktgw0316** [comment]
Thank you for your help! :+1:

**Comment by juhavlintula** [comment]
It looks like the bug was not fully fixed or it has crept back to 4.1.8.

The image IMG_5063.CR2/IMG_5063_9x16_lzn.jpg is giving me trouble (https://www.dropbox.com/sh/q4r3vx3prw2pl4b/AAABn0WNkaakNG9Xs4TTKTVHa?dl=0). If I right click the _lzn file and select convert 1440×2560 I get 1440×2559 and if I select the Convert from top the screen (Batch convert) I get 1441×2561. I have tried both Ubuntu and Windows version with same results.

-Juha

**Comment by juhavlintula** [comment]
I also reverted to 231ad93 and rebuilt LZ, but this version also gave the same results.

**Comment by juhavlintula** [comment]
I got the correct result (1440×2560) when I entered the aspect ratio (9:16) into the box manually. With the failed attempt I had selected the aspect ratio from the drop-down list.
